name: Prebuild
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        node: [lts/*]
        os: [ubuntu-20.04, macos-11, macos-12, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
    - run: npm run prebuild
    - uses: actions/upload-artifact@v3
      with:
        name: prebuilds
        path: prebuilds/*
